################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../UDHAL/UDHAL.c \
../UDHAL/UDHAL_ADC1.c \
../UDHAL/UDHAL_ADC2.c \
../UDHAL/UDHAL_GPIO.c \
../UDHAL/UDHAL_I2C.c \
../UDHAL/UDHAL_NVSINT.c \
../UDHAL/UDHAL_TIM1.c \
../UDHAL/UDHAL_TIM2.c \
../UDHAL/UDHAL_TIM3.c \
../UDHAL/UDHAL_TIM4.c \
../UDHAL/UDHAL_TIM5.c \
../UDHAL/UDHAL_TIM6.c \
../UDHAL/UDHAL_TIM9.c \
../UDHAL/UDHAL_UART.c 

C_DEPS += \
./UDHAL/UDHAL.d \
./UDHAL/UDHAL_ADC1.d \
./UDHAL/UDHAL_ADC2.d \
./UDHAL/UDHAL_GPIO.d \
./UDHAL/UDHAL_I2C.d \
./UDHAL/UDHAL_NVSINT.d \
./UDHAL/UDHAL_TIM1.d \
./UDHAL/UDHAL_TIM2.d \
./UDHAL/UDHAL_TIM3.d \
./UDHAL/UDHAL_TIM4.d \
./UDHAL/UDHAL_TIM5.d \
./UDHAL/UDHAL_TIM6.d \
./UDHAL/UDHAL_TIM9.d \
./UDHAL/UDHAL_UART.d 

OBJS += \
./UDHAL/UDHAL.obj \
./UDHAL/UDHAL_ADC1.obj \
./UDHAL/UDHAL_ADC2.obj \
./UDHAL/UDHAL_GPIO.obj \
./UDHAL/UDHAL_I2C.obj \
./UDHAL/UDHAL_NVSINT.obj \
./UDHAL/UDHAL_TIM1.obj \
./UDHAL/UDHAL_TIM2.obj \
./UDHAL/UDHAL_TIM3.obj \
./UDHAL/UDHAL_TIM4.obj \
./UDHAL/UDHAL_TIM5.obj \
./UDHAL/UDHAL_TIM6.obj \
./UDHAL/UDHAL_TIM9.obj \
./UDHAL/UDHAL_UART.obj 

OBJS__QUOTED += \
"UDHAL\UDHAL.obj" \
"UDHAL\UDHAL_ADC1.obj" \
"UDHAL\UDHAL_ADC2.obj" \
"UDHAL\UDHAL_GPIO.obj" \
"UDHAL\UDHAL_I2C.obj" \
"UDHAL\UDHAL_NVSINT.obj" \
"UDHAL\UDHAL_TIM1.obj" \
"UDHAL\UDHAL_TIM2.obj" \
"UDHAL\UDHAL_TIM3.obj" \
"UDHAL\UDHAL_TIM4.obj" \
"UDHAL\UDHAL_TIM5.obj" \
"UDHAL\UDHAL_TIM6.obj" \
"UDHAL\UDHAL_TIM9.obj" \
"UDHAL\UDHAL_UART.obj" 

C_DEPS__QUOTED += \
"UDHAL\UDHAL.d" \
"UDHAL\UDHAL_ADC1.d" \
"UDHAL\UDHAL_ADC2.d" \
"UDHAL\UDHAL_GPIO.d" \
"UDHAL\UDHAL_I2C.d" \
"UDHAL\UDHAL_NVSINT.d" \
"UDHAL\UDHAL_TIM1.d" \
"UDHAL\UDHAL_TIM2.d" \
"UDHAL\UDHAL_TIM3.d" \
"UDHAL\UDHAL_TIM4.d" \
"UDHAL\UDHAL_TIM5.d" \
"UDHAL\UDHAL_TIM6.d" \
"UDHAL\UDHAL_TIM9.d" \
"UDHAL\UDHAL_UART.d" 

C_SRCS__QUOTED += \
"../UDHAL/UDHAL.c" \
"../UDHAL/UDHAL_ADC1.c" \
"../UDHAL/UDHAL_ADC2.c" \
"../UDHAL/UDHAL_GPIO.c" \
"../UDHAL/UDHAL_I2C.c" \
"../UDHAL/UDHAL_NVSINT.c" \
"../UDHAL/UDHAL_TIM1.c" \
"../UDHAL/UDHAL_TIM2.c" \
"../UDHAL/UDHAL_TIM3.c" \
"../UDHAL/UDHAL_TIM4.c" \
"../UDHAL/UDHAL_TIM5.c" \
"../UDHAL/UDHAL_TIM6.c" \
"../UDHAL/UDHAL_TIM9.c" \
"../UDHAL/UDHAL_UART.c" 


